/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.submissiontracker.utils

import play.api.Logger

trait WelshFormNameTranslator {

  val logger: Logger = Logger(this.getClass)

  val cyFormNames: Map[String, String] = {
    Map(
      "CTRDAASUB"                                      -> "‘AA’ ar gyfer ymchwil a datblygu rhyddhad treth",
      "TSPChief"                                       -> "Actifadu bathodyn er mwyn gwneud Datganiad CHIEF",
      "HO60SUB"                                        -> "Ad-daliad o doll olewau a ddefnyddir fel tanwydd ar awyren sy’n mynd tramor",
      "HO55SUB"                                        -> "Ad-daliad rhannol o Doll Ecséis ar olew mwynol ad-daledig",
      "HO53SUB"                                        -> "Ad-daliad rhannol o Doll Olew Hydrocarbon",
      "NICNationalInsuranceRebates"                    -> "Ad-daliadau Yswiriant Gwladol CYG",
      "RepaySEISSGrantMoney"                           -> "Ad-dalu arian grant y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "RepayEatOuttoHelpOutGrant"                      -> "Ad-dalu grant y Cynllun Bwyta Allan i Helpu Allan",
      "HO50SUB"                                        -> "Ad-dalu Toll Ecséis ar Olew Mwynol a ddefnyddiwyd ar Longau Masnachol",
      "HO49SUB"                                        -> "Ad-dalu toll ecséis ar olew mwynol a ddefnyddiwyd gan gynhyrchwyr garddwriaethol",
      "ReclaimNon-UKResidentStampDutyLandTaxSurcharge" -> "Adennill Gordal Treth Dir y Tollau Stamp i Berson nad ydynt yn breswyl yn y DU",
      "L2PSUB"                                         -> "Adennill treth a dalodd cwmnïau caeedig ar fenthyciadau i gyfranogwyr",
      "ChildcareServiceMandatoryReview"                -> "Adolygiad Gorfodol Gwasanaeth Gofal Plant",
      "SEISSRequestaReviewofEligibility"               -> "Adolygiad o Gymhwystra ar gyfer y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "AdjudicatorsOfficeReview"                       -> "Adolygiad Swyddfa’r Dyfarnwr o gŵyn am CThEF",
      "IPR2"                                           -> "Adrodd am nwyddau sy’n torri’ch hawliau eiddo deallusol",
      "C179BSUB"                                       -> "Ailfewnforio cerbyd modur preifat o’r tu allan i’r Undeb Ewropeaidd (UE)",
      "CIS40SUB"                                       -> "Allgofnodi o Gynllun y Diwydiant Adeiladu (CIS) – Hawliad am ad-daliad gan unigolyn",
      "CA3821"                                         -> "Anfon cyflogeion i weithio dramor",
      "VATFPRC"                                        -> "Anfon manylion i ategu ad-daliad TAW",
      "INVALID"                                        -> "Annilys",
      "AL50SUB"                                        -> "Ardoll Agregau: Cais am driniaeth grŵp",
      "AL1SUB"                                         -> "Ardoll Agregau: Cais er mwyn cofrestru",
      "AL1ASUB"                                        -> "Ardoll Agregau: Cofrestru neu ddiwygio safle sydd eisoes yn bodoli",
      "AL51SUB"                                        -> "Ardoll Agregau: Manylion aelodau’r grŵp",
      "AL2SUB"                                         -> "Ardoll Agregau: Manylion y bartneriaeth",
      "CH995SUB"                                       -> "Awdurdodi ymgynghorydd treth ar gyfer materion Tâl Incwm Uchel Budd-dal Plant",
      "BOD2SUB"                                        -> "Bil Rhyddhau ar gyfer Rhyddhad Defnydd Terfynol gan ddefnyddio awdurdod llawn",
      "BOD4SUB"                                        -> "Bil Rhyddhau ar gyfer Rhyddhad Defnydd Terfynol: awdurdod y tollau drwy ddatganiad",
      "BOD1SUB"                                        -> "Bil Rhyddhau Prosesu Mewnol gan ddefnyddio awdurdod llawn",
      "BOD3SUB"                                        -> "Bil Rhyddhau Prosesu Mewnol: awdurdod y tollau drwy ddatganiad",
      "HO930"                                          -> "Biodanwyddau",
      "CTFACCSUB"                                      -> "Ble y delir Cronfa Ymddiriedolaeth Plant eich plentyn",
      "C117"                                           -> "C117 Gwneud cais am Weithredwr Economaidd Awdurdodedig",
      "C1181.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 1 Rhan 1",
      "C1181.2"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 1 Rhan 2",
      "C1181.3"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 1 Rhan 3",
      "C1182.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 2 Rhan 1",
      "C1183.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 3 Rhan 1",
      "C1183.2"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 3 Rhan 2",
      "C1184.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 4 Rhan 1",
      "C1185.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 5 Rhan 1",
      "C1186.1"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 6 Rhan 1",
      "C1186.2"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 6 Rhan 2",
      "C1186.3"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 6 Rhan 3",
      "C1186.4"                                        -> "C118 Gwneud cais am Weithredwr Economaidd Awdurdodedig Adran 6 Rhan 4",
      "SEISSCessationDeclarationBeforeGrantReceived" -> "Cadarnhewch p’un a ydych wedi rhoi’r gorau i fasnachu cyn y gwnaethoch hawlio grant y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "GetanXIEORI"            -> "Cael EORI XI: Gogledd Iwerddon",
      "CustomerEngagementTeam" -> "Cael help gyda materion treth ar gyfer busnes o faint canolig",
      "HO66SUB"                -> "Cais am ad-daliad o doll a dalwyd ar olewau a ddefnyddir fel tanwydd ar longau sy’n mynd tramor",
      "HO29SUB"                -> "Cais am ad-daliad o doll ecséis ar olewau a ddefnyddir at ddibenion penodol",
      "CA8480"                 -> "Cais am ad-daliad o gyfraniadau Yswiriant Gwladol Dosbarth 2",
      "CA8480SUB"              -> "Cais am ad-daliad o gyfraniadau Yswiriant Gwladol Dosbarth 2",
      "CA5610"                 -> "Cais am ad-daliad o gyfraniadau Yswiriant Gwladol Dosbarth 4",
      "CA5610SUB"              -> "Cais am ad-daliad o gyfraniadau Yswiriant Gwladol Dosbarth 4",
      "R40SUB"                 -> "Cais am ad-daliad o’r dreth a ddidynnwyd o gynilion a buddsoddiadau",
      "P50Z"                   -> "Cais am ad-daliad treth pan fyddwch wedi rhoi’r gorau i weithio: pensiwn a gyrchir yn hyblyg",
      "P50ZSUB"                -> "Cais am ad-daliad treth pan fyddwch wedi rhoi’r gorau i weithio: pensiwn a gyrchir yn hyblyg",
      "DMB-EMP"                -> "Cais am ariannu ad-daliad treth i gyflogai",
      "EMP"                    -> "Cais am ariannu ad-daliad treth i gyflogai",
      "CandE42SUB"             -> "Cais am awdurdod i weithredu man allforio dynodedig",
      "C1349SUB"               -> "Cais am awdurdodi gwasanaeth cludo rheolaidd",
      "CF411SUB"               -> "Cais am Ddiogelwch Cyfrifoldebau Cartref",
      "L5SUB"                  -> "Cais am drwydded i gynnal Masnach Ecséis",
      "CA9107SUB"              -> "Cais am dystysgrif o rwymedigaeth barhaus ar gyfer gwledydd mewn cydgytundeb",
      "PT_CertResFI"           -> "Cais am Dystysgrif Preswylio yn y DU: Gwybodaeth bellach",
      "CBOCH299e"              -> "Cais am estyniad",
      "SP5SUB"                 -> "Cais am Fynediad Dros Dro",
      "R44SUB"                 -> "Cais am God NT Morwyr",
      "MODCA2SUB"              -> "Cais am gredydau Yswiriant Gwladol dosbarth 3",
      "S690SUB"                -> "Cais am gyfarwyddyd Adran 690 neu gytuniad anffurfiol",
      "HO27SUB"                -> "Cais am gymeradwyaeth i gael rhyddhad rhag toll ecséis ar olew mwynol a ddefnyddir at ddibenion penodol",
      "SP1SUB"                 -> "Cais am Ryddhad Defnydd Terfynol",
      "SP4SUB"                 -> "Cais am Ryddhad Prosesu Allanol",
      "SP3SUB"                 -> "Cais am Ryddhad Prosesu Mewnol",
      "CA8454"                 -> "Cais am sicrwydd gofal iechyd yn yr Ardal Economaidd Ewropeaidd",
      "C1454SUB"               -> "Cais am statws allforiwr cymeradwy",
      "SP2SUB"                 -> "Cais am warws tollau",
      "CE109SUB"               -> "Cais cerbyd modur preifat am gael rhyddhad rhag yr amodau rhyddhau",
      "CCL7SUB"                -> "Cais er mwyn canslo’ch cofrestriad ar gyfer yr Ardoll Newid yn yr Hinsawdd",
      "AL7SUB"                 -> "Cais er mwyn Canslo’ch Cofrestriad Ardoll Agregau",
      "BD601SUB"               -> "Cais er mwyn cofrestru fel hyrwyddwr y loteri",
      "NRL4e"                  -> "Cais gan asiantau gosod eiddo yn y DU i weithredu cynllun Landlordiaid Dibreswyl",
      "ATSOPTOUTSUB"           -> "Cais i ddewis peidio â chael crynodeb treth blynyddol TWE",
      "DS4"                    -> "Cais i ddiwygio’ch cofrestriad am Stampiau Tollau",
      "REXSUB"                 -> "Cais i ddod yn allforiwr cofrestredig",
      "GD57"                   -> "Cais i gael eich cynnwys ar Gofrestr y Doll Hapchwarae",
      "GD60"                   -> "Cais i gael eich trin fel grŵp ar gyfer y Doll Hapchwarae",
      "NRL2e"                  -> "Cais i gael incwm rhent yn y DU heb ddidyniadau treth y DU",
      "DS3"                    -> "Cais i ganslo’ch cofrestriad am Stampiau Tollau",
      "DS1SUB"                 -> "Cais i gofrestru am Stampiau Tollau",
      "TRC1"                   -> "Cais i gofrestru ar gyfer y cynllun Derbynnydd Cofrestredig Dros Dro",
      "CP30SUB"                -> "Cais i gofrestru fel gwneuthurwr seidr neu berai",
      "EX250SUB"               -> "Cais i gofrestru fel hyrwyddwr bingo",
      "HM3SUB"                 -> "Cais i gofrestru fel mewnforiwr masnachol cofrestredig",
      "CA72A"                  -> "Cais i ohirio talu cyfraniadau Yswiriant Gwladol Dosbarth 1",
      "CA72ASUB"               -> "Cais i ohirio talu cyfraniadau Yswiriant Gwladol Dosbarth 1",
      "SA303"                  -> "Cais i ostwng taliadau ar gyfrif",
      "SPTU"                   -> "Cais i ychwanegu at Bensiwn y Wladwriaeth",
      "VAT600AASUB"            -> "Cais i ymuno â’r Cynllun Cyfrifyddu Blynyddol",
      "NRL4-5"                 -> "Cais landlord dibreswyl i asiantau gosod eiddo",
      "NRL2-3"                 -> "Cais landlord dibreswyl i gwmnïau ac ymddiriedolaethau",
      "NRL1e"                  -> "Cais landlord dibreswyl i unigolyn",
      "TSPRevocation"          -> "Canslo Cofrestriad TSP",
      "CancelGBEORI"           -> "Canslo EORI GB",
      "P46Car"                 -> "Car a ddarperir at ddefnydd preifat cyflogai neu gyfarwyddwr",
      "support-research-and-development-tax-claim" -> "Cefnogi hawliad treth ymchwil a datblygu",
      "MSBGROWTH"                                  -> "Cefnogi Twf Busnes o Faint Canolig (MSB)",
      "EX103SUB"                                   -> "Cofnod ecséis: Cwmni corfforedig / Masnachwr preifat",
      "RecordClaimsSPBP"                           -> "Cofnodi hawliadau o’r Tâl Statudol Rhieni mewn Profedigaeth",
      "IPT1"                                       -> "Cofrestriad ar gyfer Treth Premiwm Yswiriant",
      "PlasticPackagingTaxRegistration"            -> "Cofrestriad ar gyfer y Dreth Deunydd Pacio Plastig",
      "LT1"                                        -> "Cofrestriad ar gyfer y Dreth Dirlenwi",
      "CCL3SUB"                                    -> "Cofrestriad ar gyfer yr Ardoll Newid yn yr Hinsawdd",
      "CORPORATEINTERESTRESTRICTIONREGISTRATION"   -> "Cofrestriad Cyfyngiadau ar Log Corfforaethol",
      "EX250"                                      -> "Cofrestriad Hyrwyddwr Bingo",
      "GD56"                                       -> "Cofrestriad Toll Hapchwarae",
      "APD1"                                       -> "Cofrestriad y Doll Teithwyr Awyr",
      "EX103EX103ABFS"                             -> "Cofrestru ar gyfer toll ar fiodanwyddau ac amnewidion tanwydd eraill",
      "C1200HO"                                    -> "Cofrestru ar gyfer y Doll ar Nwy at ddefnydd tanwydd ffordd",
      "FuelDutyRegistration"                       -> "Cofrestru ar gyfer y Doll Tanwydd",
      "AL1AL1A"                                    -> "Cofrestru ar gyfer yr Ardoll Agregau",
      "TRNGIP"                                     -> "Cofrestru cwmni dibreswyl ar gyfer treth gorfforaeth",
      "SA4001"                                     -> "Cofrestru partner neu bartneriaeth ar gyfer Hunanasesiad",
      "SA400"                                      -> "Cofrestru partneriaeth ar gyfer Hunanasesiad",
      "41GRTSUB"                                   -> "Cofrestru ymddiriedolaeth",
      "41GRESUB"                                   -> "Cofrestru ystâd",
      "CIS304"                                     -> "Cofrestru’ch partneriaeth ar gyfer Cynllun y Diwydiant Adeiladu (CIS)",
      "CIS305"                                     -> "Cofrestru’ch partneriaeth fel isgontractwr, neu wneud cais am statws taliadau gros",
      "CF411ASUB"                                  -> "Credydau i rieni a gofalwyr",
      "TC122SUB"                                   -> "Credydau Treth: Cydymffurfiaeth",
      "TC846SUB"                                   -> "Credydau treth: Gordaliad",
      "170"                                        -> "Credydau Treth: os ydych o’r farn bod penderfyniad yn anghywir",
      "TC1133SUB"                                  -> "Credydau Treth: Rhowch wybod i ni am galedi ariannol a chostau ac incwm yr aelwyd",
      "QAHC"                                       -> "Cwmni sy’n dal asedion cymwys",
      "VCSAA"                                      -> "Cyfalaf Mentro nad yw’n statudol",
      "VCSSITR1"                                   -> "Cyfalafau Mentro",
      "P53Z"                                       -> "Cyfandaliad pensiwn a gyrchir yn hyblyg: cais am ad-daliad (y flwyddyn dreth bresennol)",
      "AAG4_PRNSUB"                                -> "Cyfeirnod ar gyfer adrodd am hyrwyddwr",
      "CA3822"                                     -> "Cyflogai sy’n mynd i weithio yn yr AEE",
      "VCSEIS1"                                    -> "Cyflwyno datganiad cydymffurfio EIS y Cynllun Buddsoddi mewn Mentrau i CThEF",
      "VCSSEIS1"                                   -> "Cyflwyno datganiad cydymffurfio SEIS1 y Cynllun Buddsoddi mewn Mentrau i CThEF",
      "P11DBSUB"                                   -> "Cyfraniadau Yswiriant Gwladol Dosbarth 1A sy’n ddyledus ar dreuliau a buddiannau",
      "DMB-SP"                                     -> "Cymorth ariannol gyda thaliadau statudol",
      "HO83SUB"                                    -> "Cynllun Delwyr Cofrestredig mewn Olew Rheoledig: Cais i datgofrestru",
      "CIS301302"                                  -> "Cynllun y Diwydiant Adeiladu (CIS) – Cofrestru’n Unigol (CIS301 - CIS302)",
      "CIS41SUB"                                   -> "Cynllun y Diwydiant Adeiladu (CIS) – Hawliad am ad-daliad gan bartner",
      "PSA1"                                       -> "Cytundeb Setliad TWE",
      "SEISSROOG"                                  -> "Cytuno i dalu grant y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "CashDeclaration"                            -> "Datgan arian parod rydych yn ei gario i mewn neu allan o’r DU",
      "NIVATTrader"                                -> "Datgan masnachau eich busnes yng Ngogledd Iwerddon",
      "MTDVAT-RegistrationNotRequiredNotification" -> "Datgan nad oes angen i’ch busnes gofrestru ar gyfer y cynllun Troi Treth yn Ddigidol (TAW)",
      "AL100"                                      -> "Datganiad Ardoll Agregau",
      "CashDeclarationNI"                          -> "Datganiad Arian Parod Gogledd Iwerddon (NI)",
      "CashDeclarationGB"                          -> "Datganiad Arian Parod Prydain Fawr (GB)",
      "HO5"                                        -> "Datganiad gan Ddelwyr Cofrestredig mewn Olewau Rheoledig",
      "HO5SUB"                                     -> "Datganiad gan Ddelwyr Cofrestredig mewn Olewau Rheoledig",
      "HO34SUB"                                    -> "Datganiad gan fasnachwr cymeradwy olewau mwynol a ddefnyddir at ddibenion penodol",
      "NRLYSUB"                                    -> "Datganiad Gwybodaeth Blynyddol Landlord Dibreswyl",
      "CA3916SUB"                                  -> "Datganiad o gyfraniadau Yswiriant Gwladol",
      "BD510"                                      -> "Datganiad Toll Bingo",
      "EX46SUB"                                    -> "Datganiad Toll Cwrw",
      "HO930SUB"                                   -> "Datganiad toll ecséis a thalu toll ar gyfer biodanwyddau ac amnewidion tanwydd eraill",
      "GD95"                                       -> "Datganiad Toll Hapchwarae",
      "BD600"                                      -> "Datganiad Toll y Loteri",
      "ESSDisclosure"                              -> "Datgelu camddefnydd o’ch system til",
      "AAG1SUB"                                    -> "Datgelu Cynllun Arbed Treth – hyrwyddwr y cynllun",
      "AAG4DSUB"                                   -> "Datgelu cynllun arbed treth: hysbysiad o gyfeirnod y cynllun",
      "HO6SUB"                                     -> "Delwyr Cofrestredig mewn Olew Rheoledig: Manylion y Bartneriaeth",
      "HO4SuppSUB"                                 -> "Delwyr Cofrestredig mewn Olewau Rheoledig: cais i gyflwyno datganiadau’n flynyddol",
      "Qualifyingcompaniesexemptionelection"       -> "Dewis cwmnïau cymwys i gael eu heithrio",
      "CIVexemptionelection"                       -> "Dewis gan endid trwy ddull buddsoddi ar y cyd (CIV) i gael ei eithrio",
      "Transparencyelection"                       -> "Dewis Tryloywder",
      "CORPORATEINTERESTRESTRICTIONREVOCATIONS"    -> "Diddymu Cyfyngiadau ar Log Corfforaethol",
      "JobRetentionSchemeRevocation"               -> "Diddymu’r Cynllun Cadw Swyddi yn sgil Coronafeirws",
      "UpdateGBEORIDetails"                        -> "Diweddaru Manylion EORI GB",
      "C81SUB"                                     -> "Diwygiad i ddatganiad allforio/ail-allforio",
      "P11DAmendments"                             -> "Diwygiadau i’r P11D",
      "P11DDbAmendments"                           -> "Diwygiadau i’r P11D(b)",
      "DutyDeferrmentAccountAmendorCancel"         -> "Diwygio neu Ganslo Cyfrif Gohirio Tollau",
      "ADR"                                        -> "Dull Amgen o Ddatrys Anghydfod",
      "SA700"                                      -> "Ffurflen Dreth i gwmni dibreswyl sy’n agored i dreth incwm",
      "CORPORATEINTERESTRETURNS"                   -> "Ffurflen Dreth Llog Corfforaethol",
      "HO4SUB"                                     -> "Ffurflen gais am gymeradwyaeth Delwyr Cofrestredig mewn Olew Rheoledig",
      "EX55SUB"                                    -> "Ffurflen gais ar gyfer tanwydd a ddefnyddiwyd i gynhyrchu trydan",
      "CASCA1SUB"                                  -> "Ffurflen gofrestru Clwb Chwaraeon Amatur Cymunedol",
      "NMWCompSUB"                                 -> "Ffurflen Gŵyn o ran Hawliau Cyflog a Gwaith",
      "PPTFinalReturn"                             -> "Ffurflen Treth Deunydd Pacio Plastig Derfynol a diwygiadau",
      "LT100"                                      -> "Ffurflen Treth Dirlenwi",
      "CBOCH459e"                                  -> "Gadael addysg amser llawn, nad yw’n addysg uwch neu hyfforddiant",
      "P85"                                        -> "Gadael y DU i hawlio rhyddhad treth neu unrhyw ad-daliad treth sy’n ddyledus i chi",
      "ask-for-extension-for-chief-import-declarations"   -> "Gofyn am estyniad ar gyfer Datganiadau Mewnforio CHIEF",
      "AskaquestionabouttheCoronavirusJobRetentionScheme" -> "Gofyn cwestiwn am y Cynllun Cadw Swyddi yn sgil Coronafeirws",
      "SEISSRequestaReviewofEligibility-NewChild" -> "Gofyn i CThEF gadarnhau i chi gael plentyn newydd a bod hyn wedi effeithio ar eich cymhwystra ar gyfer y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "CCG1"                                                -> "Gwarant Gynhwysfawr y Tollau",
      "TrustRegistrationService"                            -> "Gwasanaeth Cofrestru Ymddiriedolaethau – gwneud cais am ddata",
      "TrustReporting"                                      -> "Gwasanaeth Cofrestru Ymddiriedolaethau – rhoi gwybod am anghysondeb",
      "DO4SUB"                                              -> "Gwasanaeth Datgelu Digidol",
      "PODS"                                                -> "Gwasanaeth Digidol Pensiynau Ar-lein",
      "FISSUB"                                              -> "Gwasanaeth Ymchwilio i Dwyll",
      "TSP"                                                 -> "Gweithdrefnau Symlach Dros Dro",
      "CA8421i"                                             -> "Gweithio mewn 2 neu fwy o wledydd yn yr Ardal Economaidd Ewropeaidd",
      "CA8421SUB"                                           -> "Gweithio mewn 2 neu fwy o wledydd yn yr Ardal Economaidd Ewropeaidd",
      "InternationalCaseworkersCA3822"                      -> "Gwella Gweithwyr Achos Rhyngwladol (Cyflogai)",
      "InternationalCaseworkersCA3837"                      -> "Gwella Gweithwyr Achos Rhyngwladol (Cyflogwr)",
      "Reviewself-employmentincomesupportschemegrantamount" -> "Gwneud cais am Adolygiad o Swm y Grant SEISS",
      "AdvancePaymentSPBP"                                  -> "Gwneud cais am daliad ymlaen llaw o dâl statudol rhieni mewn profedigaeth",
      "ApplyforPartialExemptionSpecialMeasures"             -> "Gwneud Cais am Ddull Eithriad Rhannol Arbennig",
      "WMW1SUB"                             -> "Gwneud cais am drwydded fel cynhyrchydd gwin neu win a wnaed, neu fel tyfwr masnachol",
      "RES1"                                -> "Gwneud cais am dystysgrif preswylio",
      "PT_CertOfRes"                        -> "Gwneud cais am dystysgrif preswylio yn y DU",
      "CA5403"                              -> "Gwneud cais am gael eich rhif Yswiriant Gwladol ar bapur",
      "DutyDeferrmentAccount"               -> "Gwneud cais am gyfrif gohirio tollau",
      "GrowthSupportService"                -> "Gwneud cais am gymorth twf ar gyfer busnes o faint canolig",
      "IPR1"                                -> "Gwneud cais am gymryd camau i ddiogelu’ch hawliau eiddo deallusol",
      "GuaranteeWaiver"                     -> "Gwneud cais am ildiad gwarant",
      "IPR3"                                -> "Gwneud cais am ymestyn eich cais i ddiogelu’ch eiddo deallusol",
      "P626PSARequestAmend"                 -> "Gwneud cais i ddiwygio PSA (Cytundeb Setliad TWE)",
      "EX72"                                -> "Gwneud cais i ddod yn Anfonwr Cofrestredig",
      "EX60"                                -> "Gwneud cais i fod yn berchennog ar nwyddau y gohiriwyd tollau arnynt ac a gedwir mewn warws ecséis",
      "EX64"                                -> "Gwneud cais i fod yn gynrychiolydd tollau",
      "ConsultationComplaints"              -> "Gwneud cwyn am Ymgynghoriadau CThEF",
      "GENCOMPSUB"                          -> "Gwneud cwyn ar-lein",
      "GENCOMBUSSUB"                        -> "Gwneud cwyn busnes ar-lein",
      "PTCOMPSUB"                           -> "Gwneud eich cwyn ar-lein",
      "Makeclaimforextendedlosscarryback"   -> "Gwneud hawliad i gario colled yn ôl dros gyfnod estynedig",
      "PPTRequestaRefund"                   -> "gwneud-cais-am-ad-daliad-treth-deunydd-pacio-plastig",
      "CP33SUB"                             -> "Hawliad am eithriad rhag cofrestru gan wneuthurwr seidr neu berai sydd ar werth",
      "R38EXPATSUB"                         -> "Hawliad treth person alltud",
      "CISREPAYSUB"                         -> "Hawlio ad-daliad o ddidyniadau oddi ar eich taliadau Cynllun y Diwydiant Adeiladu",
      "VAT126"                              -> "Hawlio ad-daliad TAW os nad ydych wedi cofrestru ar gyfer TAW",
      "R39_EN"                              -> "Hawlio ad-daliad treth",
      "P50"                                 -> "Hawlio ad-daliad treth pan fyddwch wedi rhoi’r gorau i weithio",
      "P50SUB"                              -> "Hawlio ad-daliad treth pan fyddwch wedi rhoi’r gorau i weithio",
      "EX597"                               -> "Hawlio Rhyddhad Cynhwysion Alcoholaidd",
      "ClaimSPBP"                           -> "Hawlio Tâl Statudol Rhieni mewn Profedigaeth",
      "CSR"                                 -> "Hunanadrodd Corfforaethol",
      "SAASUB"                              -> "Hunanasesiad: apêl yn erbyn cosb am gyflwyno’n hwyr",
      "SACSUB"                              -> "Hunanasesiad: Gwneud cais i gael eich tynnu o Hunanasesiad",
      "CE930BSUB"                           -> "Hysbysiad i gyflenwi nwy at ddefnydd tanwydd ffordd mewn cerbydau ffordd",
      "NotifyIntenttoDiscloseCJRSOverclaim" -> "Hysbysiad o Fwriad i Ddatgelu Gorhawlio ar gyfer y Cynllun Cadw Swyddi yn sgil Coronafeirws",
      "EX75"                                -> "Hysbysiad o fwriad i hawlio ad-daliad",
      "PAYENiCoCSUB"                        -> "Hysbysiad o newid mewn manylion personol",
      "LT1BSUB"                             -> "Hysbysiad o newidiadau i fanylion safle o ran y Dreth Dirlenwi",
      "ISAMNOCSUB"                          -> "Hysbysiad o newidiadau rheolwr ISA",
      "VAT652"                              -> "Hysbysiad o wallau ar Ffurflenni TAW",
      "RDPreNotification"                   -> "Hysbysiad Ymlaen Ymchwil a Datblygu",
      "GD58"                                -> "Hysbysiad ynghylch safle",
      "NIGiantsSubsidiaries"                -> "Is-gwmnïau Giants Gogledd Iwerddon",
      "OverseasSABankDetails"               -> "Manylion Banc Hunanasesiad Tramor",
      "LT2SUB"                              -> "Manylion y bartneriaeth o ran y Dreth Dirlenwi",
      "ChangeanXIEORI"                      -> "Newid EORI XI",
      "CHV1sub"                             -> "Newid manylion eich elusen",
      "CBOCH1702e"                          -> "Newid yn Amgylchiadau’r Hawliwr (CoC)",
      "CBOCLCOCSUBpreviouslyCBOCH1702e"     -> "Newid yn Amgylchiadau’r Hawliwr (CoC)",
      "CBOCHCOCSUBpreviouslyCH102"          -> "Newid yn Amgylchiadau’r Plentyn (CoC)",
      "CH102"                               -> "Newid yn amgylchiadau’r plentyn (CoC)",
      "CCL2ASUB"                            -> "Newidiadau i Fanylion y Bartneriaeth",
      "CE930"                               -> "Nwy at ddefnydd Tanwydd Ffordd",
      "HO74SUB"                             -> "Olew trwm ad-daledig a ddefnyddir fel tanwydd: amcangyfrif pellach yn dilyn newid i gyfradd doll",
      "HO72SUB"                             -> "Olew trwm ad-daledig a ddefnyddir fel tanwydd: amcangyfrif y doll sy’n daladwy gennych",
      "HO75SUB"                             -> "Olew trwm ad-daledig a ddefnyddir fel tanwydd: datganiad diwedd cyfnod",
      "HO73SUB" -> "Olew trwm ad-daledig a ddefnyddir fel tanwydd: taliad a thaliad atodol o olew trwm ad-daledig a fydd yn cael ei ddefnyddio fel tanwydd",
      "CBOCH297e"             -> "Parhau mewn addysg amser llawn, nad yw’n addysg uwch neu hyfforddiant",
      "P53"                   -> "Pensiwn bach yn cael ei gymryd fel cyfandaliad: cais am ad-daliad",
      "P53SUB"                -> "Pensiwn bach yn cael ei gymryd fel cyfandaliad: cais am ad-daliad",
      "CE813SUB"              -> "Prosesu Mewnol (IP) – Hawliad i adennill ad-daliad toll",
      "Vishing"               -> "Rhoi gwybod am alwad ffôn amheus sy’n honni ei bod gan CThEF",
      "RCGTSUB"               -> "Rhoi gwybod am Dreth Enillion Cyfalaf ar eiddo yn y DU",
      "NIPBE"                 -> "Rhoi gwybod i CThEF – Sefydliad Parhaol yng Ngogledd Iwerddon",
      "UncertainTaxTreatment" -> "Rhoi gwybod i CThEF am achos o drin treth mewn ffordd ansicr",
      "Tellhmrcyouareregisteredforvatimportonestopshopineu" -> "Rhoi gwybod i CThEF eich bod wedi’ch cofrestru ar gyfer y gwasanaeth un cam ar gyfer TAW o ran mewnforio yn yr UE",
      "NoneligibilitySPBP" -> "Rhoi gwybod i gyflogai nad yw’n gymwys i gael tâl statudol rhieni mewn profedigaeth",
      "TES3"               -> "Rhoi gwybod i ni am eich Budd-daliadau Trethadwy’r Wladwriaeth",
      "TES7"               -> "Rhoi gwybod i ni am eich lwfans rhydd o dreth",
      "TES2"               -> "Rhoi gwybod i ni am fuddiannau cwmni",
      "TES4"               -> "Rhoi gwybod i ni am incwm arall",
      "TES5"               -> "Rhoi gwybod i ni am incwm o fuddsoddiadau",
      "TES1"               -> "Rhoi gwybod i ni am incwm o gyflogaeth neu bensiwn",
      "BBSI5SUB-"          -> "Rhoi gwybod i ni am log banc a chymdeithasau adeiladu’r DU",
      "TES_FIN_SUB"        -> "Rhoi gwybod i ni sut hoffech dalu’r dreth amcangyfrifedig sydd arnoch",
      "LT769SUB"           -> "Rhoi manylion ansolfedd mewn perthynas â’r Dreth Dirlenwi",
      "NETPOverseasUKVAT-registeredtraders-non-establishedtaxpayers" -> "Rhoi manylion banc ar gyfer masnachwr tramor sydd wedi cofrestru ar gyfer TAW yn y DU",
      "MODnotify-hmrc-about-uk-armed-forces-customs-declaration" -> "Rhowch wybod i CThEF am ddatganiad tollau Lluoedd Arfog y DU",
      "IOSSDe-registration" -> "Rhowch wybod i CThEF am newidiadau i gofrestriad gyda’r gwasanaeth un cam ar gyfer TAW o ran mewnforio yn yr UE",
      "P87SUB"              -> "Rhyddhad treth ar gyfer treuliau cyflogaeth",
      "SEISSTellHMRCaboutamendmenttoTaxReturn"    -> "SEISS – Rhoi gwybod i CThEF am ddiwygiad i Ffurflen Dreth",
      "SettleDisguisedRenumerationasanIndividual" -> "Setlo Tâl Cuddiedig fel Unigolyn",
      "CBOptIn"                                   -> "Tâl Treth Budd-dal Plant Incwm Uchel",
      "P55"                                       -> "Taliad pensiwn a gyrchir yn hyblyg: cais am ad-daliad (y flwyddyn dreth bresennol)",
      "P55SUB"                                    -> "Taliad pensiwn a gyrchir yn hyblyg: cais am ad-daliad (y flwyddyn dreth bresennol)",
      "HO101SUB"                                  -> "Talu ad-daliad ar olew trwm arall a gyflenwyd ar gyfer gwresogi neu at ddefnydd mewn injan",
      "HO105SUB"                                  -> "Talu toll ar danwydd tyrbin hedfan ar gyfer hedfan at bleser preifat",
      "HO10"                                      -> "Tanwydd a Dynnwyd o Warws",
      "EX46VATSUB"                                -> "TAW ar ddiodydd alcoholaidd",
      "GD94"                                      -> "Toll Hapchwarae – Taliad ar gyfrif",
      "HO80SUB"                                   -> "Toll Tanwydd – Cofrestriad ar gyfer hawlio rhyddhad ar doll tanwydd",
      "HO81SUB"                                   -> "Toll Tanwydd – Hawliad am ryddhad ar doll tanwydd gwledig",
      "APD2"                                      -> "Toll Teithwyr Awyr",
      "ATEDPRBCSUB"                               -> "Treth Flynyddol ar Anheddau wedi’u Hamgáu (ATED) – Gwirio’r Band Cyn Cyflwyno Ffurflen ATED",
      "CTDormancy"                                -> "Treth Gorfforaeth Segur",
      "IPT100"                                    -> "Treth Premiwm Yswiriant",
      "TOR"                                       -> "Trosglwyddo Man Preswylio",
      "MCA-FORM18SUB"                             -> "Trosglwyddo’r Lwfans Pâr Priod",
      "EXBFPSUB"                                  -> "TWE – hysbysiad o fuddiannau a delir drwy’r gyflogres",
      "EXBENoRtnsub"                              -> "TWE – Nid oes datganiad cyfraniadau Yswiriant Gwladol Dosbarth 1A",
      "P350"                                      -> "TWE: Dewis ar gyfer llenwi Datganiad Blynyddol y Cyflogwr",
      "NIProtocolVATTraderWithdrawal"             -> "Tynnu’n ôl o Brotocol Gogledd Iwerddon ar gyfer TAW",
      "CreativeIndustriestaxreliefevidencetosupportclaim" -> "Tystiolaeth i ategu’r hawliad am ryddhad treth y diwydiant creadigol",
      "CA3822SUB"                                         -> "Tystysgrif o rwymedigaeth barhaus pan fydd cyflogai’n mynd i weithio dramor",
      "RDEC"                                              -> "Ymchwil a Datblygu",
      "RDSME"                                             -> "Ymchwil a Datblygu (MBaCh)",
      "penalty"                                           -> "Ymholiad ynghylch Cosb (Ffurflen Gyfathrebu’n Ddiogel)",
      "PlasticPackagingTaxEnquiry"                        -> "Ymholiad ynghylch y Dreth Deunydd Pacio Plastig",
      "CDSEnquiries"                                      -> "Ymholiad ynghylch y Gwasanaeth Datganiadau Tollau (CDS)",
      "CA307SUB"     -> "Yswiriant Gwladol – hawlio ad-daliad o gyfraniadau a dalwyd i’r DU tra oeddech yn gweithio dramor",
      "4WRO"         -> "Credyd treth digidol - Newid mewn amgylchiadau",
      "575TSUB"      -> "Hysbysiad trosglwyddo lwfansau Treth Incwm sydd dros ben i’ch priod neu bartner sifil",
      "CA3837SUB"    -> "Cais i gadarnhau y byddwch yn talu Yswiriant Gwladol y DU tra’n hunangyflogedig dramor dros dro",
      "CA3916"       -> "Gwneud cais am ddatganiad o Gyfraniadau Yswiriant Gwladol (CYG)",
      "CA8454SUB"    -> "Cais am sicrwydd gofal iechyd yn yr UE, yr Ardal Economaidd Ewropeaidd neu yn y Swistir",
      "CBOCH297SUB"  -> "Rhowch wybod i’r Swyddfa Budd-dal Plant fod eich plentyn yn parhau ag addysg neu hyfforddiant cymeradwy",
      "CBOCH459SUB"  -> "Rhowch wybod i’r Swyddfa Budd-dal Plant fod eich plentyn wedi gadael addysg neu hyfforddiant cymeradwy",
      "CCD"          -> "Herio penderfyniad ynghylch cais i’r Gwasanaeth Gofal Plant",
      "CF411"        -> "Cais am Ddiogelwch Cyfrifoldebau Cartref",
      "CF411A"       -> "Cais am gredydau ar gyfer rhieni a gofalwyr",
      "CTUTR"        -> "Gwneud cais am Gyfeirnod Unigryw y Trethdalwr ar gyfer Treth Gorfforaeth",
      "FORM18SUB"    -> "Trosglwyddo’r Lwfans Pâr Priod",
      "INT-NATIONAL" -> "Credyd treth digidol - Newid mewn amgylchiadau",
      "P1"           -> "Credyd treth digidol - Newid mewn amgylchiadau",
      "SDLT16"       -> "Gwneud cais am ad-daliad o 3% ar Dreth Dir y Tollau Stamp",
      "SDLT16SUB"    -> "Gwneud cais am ad-daliad o 3% ar Dreth Dir y Tollau Stamp",
      "vol-overpay"  -> "SEISS - Rhoi gwybod i CThEF am ddiwygiad i’ch Ffurflen Dreth",
      "vol-repay1"   -> "Ad-dalu arian grant y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "vol-repay2"   -> "Ad-dalu arian grant y Cynllun Cymhorthdal Incwm Hunangyflogaeth",
      "WTCAPSUB"     -> "Credydau treth: os ydych o’r farn bod penderfyniad yn anghywir"
    )
  }

  def getFormNameInWelsh(formId: String): String = cyFormNames.getOrElse(formId, formId)
}
