/*
 * Copyright 2023 HM Revenue & Customs
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package uk.gov.hmrc.submissiontracker.services

class FormNameService {

  val FormNames: Map[String, String] = {
    Map(
      "4WRO"                                                         -> "Tax Credit Digital Change of Circumstance",
      "41GRESUB"                                                     -> "Registration of an estate",
      "41GRTSUB"                                                     -> "Registration of a trust",
      "170"                                                          -> "Tax Credits: if you think a decision is wrong",
      "575TSUB"                                                      -> "Notice of transfer of surplus Income Tax allowances  to your spouse or civil partner",
      "AAG1SUB"                                                      -> "Disclosure Of Avoidance Scheme - scheme promoter",
      "AAG4_PRNSUB"                                                  -> "Report of promoter reference number",
      "AAG4DSUB"                                                     -> "Disclosure of avoidance scheme: notification of scheme reference number",
      "AdjudicatorsOfficeReview"                                     -> "Adjudicator’s Office Review of an HMRC complaint",
      "ADR"                                                          -> "Alternative Dispute Resolution",
      "AdvancePaymentSPBP"                                           -> "Apply for advance payment statutory parental bereavement pay",
      "AL1AL1A"                                                      -> "Register for Aggregates Levy",
      "AL1ASUB"                                                      -> "Aggregates Levy: Register or amend an existing site",
      "AL1SUB"                                                       -> "Aggregates Levy: Application to register",
      "AL2SUB"                                                       -> "Aggregates Levy: Partnership details",
      "AL7SUB"                                                       -> "Application to Cancel Your Aggregates Levy Registration",
      "AL50SUB"                                                      -> "Aggregates Levy: Application for group treatment",
      "AL51SUB"                                                      -> "Aggregates Levy: Group member details",
      "AL100"                                                        -> "Aggregates Levy Return",
      "APD1"                                                         -> "Air Passenger Duty Registration",
      "APD2"                                                         -> "Air Passenger Duty",
      "ApplyforPartialExemptionSpecialMeasures"                      -> "Apply for Partial Exemption Special Measures",
      "ask-for-extension-for-chief-import-declarations"              -> "Ask for extension for Chief Import Declarations",
      "AskaquestionabouttheCoronavirusJobRetentionScheme"            -> "Ask a question about the Coronavirus Job Retention Scheme",
      "ATEDPRBCSUB"                                                  -> "Annual Tax on Enveloped Dwellings (ATED) - Pre-Return Banding Check",
      "ATSOPTOUTSUB"                                                 -> "Request to opt out of receiving your PAYE annual tax summary",
      "BBSI5SUB"                                                     -> "Tell us about UK bank and building society interest",
      "BD510"                                                        -> "Bingo Duty Return",
      "BD600"                                                        -> "Lottery Duty Return",
      "BD601SUB"                                                     -> "Application to register as a lottery promoter",
      "BOD1SUB"                                                      -> "Inward Processing Bill of Discharge using a full authorisation",
      "BOD2SUB"                                                      -> "Bill of discharge for End-Use Relief using a full authorisation",
      "BOD3SUB"                                                      -> "Inward Processing bill of discharge: customs authorisation by declaration",
      "BOD4SUB"                                                      -> "End-Use relief bill of discharge: customs authorisation by declaration",
      "C81SUB"                                                       -> "Amendment to export/re-export declaration",
      "C117"                                                         -> "C117 Apply for Authorised Economic Operator",
      "C179BSUB"                                                     -> "Re-importation of an private motor vehicle from outside the European Union (EU)",
      "C1200HO"                                                      -> "Register for Duty on Gas for use as road fuel",
      "C1349SUB"                                                     -> "Application for authorisation of a regular shipping service",
      "C1454SUB"                                                     -> "Application for approved exporter status",
      "C1181.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 1 Part 1",
      "C1181.2"                                                      -> "C118 Apply for Authorised Economic Operator Section 1 Part 2",
      "C1181.3"                                                      -> "C118 Apply for Authorised Economic Operator Section 1 Part 3",
      "C1182.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 2 Part 1",
      "C1183.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 3 Part 1",
      "C1183.2"                                                      -> "C118 Apply for Authorised Economic Operator Section 3 Part 2",
      "C1184.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 4 Part 1",
      "C1185.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 5 Part 1",
      "C1186.1"                                                      -> "C118 Apply for Authorised Economic Operator Section 6 Part 1",
      "C1186.2"                                                      -> "C118 Apply for Authorised Economic Operator Section 6 Part 2",
      "C1186.3"                                                      -> "C118 Apply for Authorised Economic Operator Section 6 Part 3",
      "C1186.4"                                                      -> "C118 Apply for Authorised Economic Operator Section 6 Part 4",
      "CA72A"                                                        -> "Application for deferment of payment of Class 1 National Insurance contributions",
      "CA72ASUB"                                                     -> "Application for deferment of payment of Class 1 National Insurance contributions",
      "CA307SUB"                                                     -> "National Insurance - claim refund of UK contributions paid while working abroad",
      "CA3821"                                                       -> "Sending employees to work abroad",
      "CA3822"                                                       -> "Employees going to work in EEA",
      "CA3822SUB"                                                    -> "Certificate of continuing liability when employees are going to work abroad",
      "CA3837SUB"                                                    -> "Application to confirm you will pay UK National Insurance while self-employed abroad temporarily",
      "CA3916"                                                       -> "Request a statement of National Insurance Contributions (NICs)",
      "CA3916SUB"                                                    -> "Statement of National Insurance contributions",
      "CA5403"                                                       -> "Request National Insurance number in writing",
      "CA5610"                                                       -> "Application for refund of Class 4 National Insurance contributions",
      "CA5610SUB"                                                    -> "Application for refund of Class 4 National Insurance contributions",
      "CA8421i"                                                      -> "Working in 2 or more countries in the European Economic Area",
      "CA8421SUB"                                                    -> "Working in 2 or more countries in the European Economic Area",
      "CA8454"                                                       -> "Application for healthcare cover in the European Economic Area",
      "CA8454SUB"                                                    -> "Application for healthcare cover in the EU, European Economic Area or Switzerland",
      "CA8480"                                                       -> "Application for refund of Class 2 National Insurance contributions",
      "CA8480SUB"                                                    -> "Application for refund of Class 2 National Insurance contributions",
      "CA9107SUB"                                                    -> "Application for certificate of continuing liability for Reciprocal Agreement countries",
      "CancelGBEORI"                                                 -> "Cancel GB EORI",
      "CandE42SUB"                                                   -> "Application for authorisation to operate a designated export place",
      "CASCA1SUB"                                                    -> "Community Amateur Sports Club registration form",
      "CashDeclaration"                                              -> "Declare cash you carry into or out of the Uk",
      "CashDeclarationGB"                                            -> "Cash Declaration GB",
      "CashDeclarationNI"                                            -> "Cash Declaration NI",
      "CBOCH297e"                                                    -> "Staying in full-time, non-advanced education or training",
      "CBOCH297SUB"                                                  -> "Tell the Child Benefit Office that your child is staying in approved education or training",
      "CBOCH299e"                                                    -> "Extension application",
      "CBOCH459e"                                                    -> "Leaving full-time, non-advanced education or training",
      "CBOCH459SUB"                                                  -> "Tell the Child Benefit office that your child has left approved education or training",
      "CBOCH1702e"                                                   -> "Claimant Change of Circumstances (CoC)",
      "CBOCHCOCSUBpreviouslyCH102"                                   -> "Child Change of Circumstance (CoC)",
      "CBOCLCOCSUBpreviouslyCBOCH1702e"                              -> "Claimant Change of Circumstance (CoC)",
      "CBOptIn"                                                      -> "High Income Child Benefit Tax Charge",
      "CCD"                                                          -> "Challenge a Childcare Service application decision",
      "CCG1"                                                         -> "Customs Comprehensive Guarantee",
      "CCL2ASUB"                                                     -> "Changes to Partnership Details",
      "CCL3SUB"                                                      -> "Climate Change Levy Registration",
      "CCL7SUB"                                                      -> "Application to cancel your Climate Change Levy registration",
      "CDSEnquiries"                                                 -> "Customs Declaration Service (CDS) enquiry",
      "CE109SUB"                                                     -> "Private motor vehicle application for release from conditions of relief",
      "CE813SUB"                                                     -> "Inward Processing (IP) drawback repayment claim",
      "CE930"                                                        -> "Gas as Road Fuel",
      "CE930BSUB"                                                    -> "Notification to supply gas for use as fuel in road vehicles",
      "CF411"                                                        -> "Application for Home Responsibilities Protection",
      "CF411A"                                                       -> "Application for credits for parents and carers",
      "CF411ASUB"                                                    -> "Credits for parents and carers",
      "CF411SUB"                                                     -> "Application for Home Responsibilities Protection",
      "CH102"                                                        -> "Child change of circumstances (CoC)",
      "CH995SUB"                                                     -> "Authorising a tax adviser for High Income Child Benefit charge matters",
      "ChangeanXIEORI"                                               -> "Change an XI EORI",
      "ChildcareServiceMandatoryReview"                              -> "Childcare Service Mandatory Review",
      "CHV1sub"                                                      -> "Change the details of your charity",
      "CIS40SUB"                                                     -> "Sign out Construction Industry Scheme (CIS) - Individual’s repayment claim",
      "CIS41SUB"                                                     -> "Construction Industry Scheme (CIS) - Partner’s Repayment Claim",
      "CIS304"                                                       -> "Register your partnership for Construction Industry Scheme (CIS)",
      "CIS305"                                                       -> "Register your company as a subcontractor, or apply for gross payment status",
      "CIS301302"                                                    -> "Construction Industry Scheme (CIS) - Individual Registration (CIS301 - CIS302)",
      "CISREPAYSUB"                                                  -> "Claim repayment of deductions from your Construction Industry Scheme payments",
      "CIVexemptionelection"                                         -> "CIV exemption election",
      "ClaimSPBP"                                                    -> "Claim Statutory Parental Bereavement Pay",
      "ConsultationComplaints"                                       -> "Make a complaint about HMRC Consulations",
      "CORPORATEINTERESTRESTRICTIONREGISTRATION"                     -> "Corporate Interest Restriction Registration",
      "CORPORATEINTERESTRESTRICTIONREVOCATIONS"                      -> "Corporate Interest Restriction Revocation",
      "CORPORATEINTERESTRETURNS"                                     -> "Corporate Interest Returns",
      "CP30SUB"                                                      -> "Application to register as a cider or perry maker",
      "CP33SUB"                                                      -> "Claim for exemption from registration by a maker of cider or perry for sale",
      "CreativeIndustriestaxreliefevidencetosupportclaim"            -> "Creative Industries tax relief evidence to support claim",
      "CSR"                                                          -> "Corporate Self Reporting",
      "CTDormancy"                                                   -> "Corporation Tax Dormancy",
      "CTFACCSUB"                                                    -> "Where is your child’s Child Trust Fund held",
      "CTRDAASUB"                                                    -> "AA for research development tax relief",
      "CTUTR"                                                        -> "Request a corporation tax unique tax reference number",
      "CustomerEngagementTeam"                                       -> "Get help with tax issues for a mid-sized business",
      "DMB-EMP"                                                      -> "Application for funding a tax refund for an employee",
      "DMB-SP"                                                       -> "Financial help with statutory payments",
      "DO4SUB"                                                       -> "Digital Disclosure Service",
      "DS1SUB"                                                       -> "Application to register for Duty Stamps",
      "DS3"                                                          -> "Application to cancel Duty Stamps registration",
      "DS4"                                                          -> "Application to amend Duty Stamps registration",
      "DutyDeferrmentAccount"                                        -> "Apply for a duty deferment account",
      "DutyDeferrmentAccountAmendorCancel"                           -> "Duty Deferrment Account Amend or Cancel",
      "EMP"                                                          -> "Application for funding a tax refund for an employee",
      "ESSDisclosure"                                                -> "Make a disclosure about misusing your till system",
      "EX46SUB"                                                      -> "Beer Duty Return",
      "EX46VATSUB"                                                   -> "VAT due on alcoholic beverages",
      "EX55SUB"                                                      -> "Claim form for fuel used to generate electricity",
      "EX60"                                                         -> "Application to be an owner of duty suspended goods held in excise warehouses",
      "EX64"                                                         -> "Application to be a duty representative",
      "EX72"                                                         -> "Application to be a Registered Consignor",
      "EX75"                                                         -> "Notice of intention to claim drawback",
      "EX103EX103ABFS"                                               -> "Register for duty on biofuels and other fuel substitutes",
      "EX103SUB"                                                     -> "Excise entry: Incorporated company / Private trader",
      "EX250"                                                        -> "Bingo Promoter Registration",
      "EX250SUB"                                                     -> "Application for registration as a bingo promoter",
      "EX597"                                                        -> "Claim Alcoholic Ingredients Relief",
      "EXBENoRtnsub"                                                 -> "PAYE - No return of Class 1A National Insurance contributions",
      "EXBFPSUB"                                                     -> "PAYE-notification of payrolled benefits",
      "FISSUB"                                                       -> "Fraud Investigation Service",
      "FORM18SUB"                                                    -> "Transferring the married couples allowance",
      "FuelDutyRegistration"                                         -> "Register for Fuel Duty",
      "GD56"                                                         -> "Gaming Duty Registration",
      "GD57"                                                         -> "Application for inclusion on the Gaming Duty Register",
      "GD58"                                                         -> "Notification of premises",
      "GD60"                                                         -> "Application for Group Treatment for Gaming Duty",
      "GD94"                                                         -> "Gaming Duty Payment on Account",
      "GD95"                                                         -> "Gaming Duty Return",
      "GENCOMBUSSUB"                                                 -> "Make a business complaint online",
      "GENCOMPSUB"                                                   -> "Make a complaint online",
      "GetanXIEORI"                                                  -> "Get an XI EORI: Northern Ireland",
      "GrowthSupportService"                                         -> "Request growth support for mid-sized business",
      "GuaranteeWaiver"                                              -> "Apply for a guarantee waiver",
      "HM3SUB"                                                       -> "Application to register as a registered commercial importer",
      "HO4SUB"                                                       -> "Registered Dealers in Controlled Oil Application form for approval",
      "HO4SuppSUB"                                                   -> "Registered Dealers in Controlled Oils: application to submit annual returns",
      "HO5"                                                          -> "Return by Registered Dealers in Controlled Oils",
      "HO5SUB"                                                       -> "Return by Registered Dealers in Controlled Oils",
      "HO6SUB"                                                       -> "Registered Dealers in Controlled Oil: Partnership Details",
      "HO10"                                                         -> "Fuel Removed From Warehouse",
      "HO27SUB"                                                      -> "Application for approval to obtain relief from excise duty on mineral oil put to certain uses",
      "HO29SUB"                                                      -> "Claim for repayment of excise duty on oils put to certain uses",
      "HO34SUB"                                                      -> "Return by an approved trader in mineral oils for certain uses",
      "HO49SUB"                                                      -> "Repayment of excise duty on mineral oil used by horticultural producers",
      "HO50SUB"                                                      -> "Repayment of Excise Duty Mineral Oil used on Commercial Vessels",
      "HO53SUB"                                                      -> "Partial repayment of Hydrocarbon Oil Duty",
      "HO55SUB"                                                      -> "Partial repayment of rebated Excise Duty mineral oil",
      "HO60SUB"                                                      -> "Drawback of duty oils used as fuel on foreign going aircraft",
      "HO66SUB"                                                      -> "Claim for drawback of duty paid on oils used as fuel on foreign-going vessels",
      "HO72SUB"                                                      -> "Rebated heavy oil used as fuel: estimate your duty payable",
      "HO73SUB"                                                      -> "Rebated heavy oil used as fuel: supplementary and payment of rebated heavy oil to be used as fuel",
      "HO74SUB"                                                      -> "Rebated heavy oil used as fuel: further estimate following a change of duty rate",
      "HO75SUB"                                                      -> "Rebated heavy oil used as fuel: period end return",
      "HO80SUB"                                                      -> "Fuel Duty - Registration to claim fuel duty relief",
      "HO81SUB"                                                      -> "Fuel Duty - Claim for rural fuel duty relief",
      "HO83SUB"                                                      -> "Registered Dealers in Controlled Oil Scheme: request to deregister",
      "HO101SUB"                                                     -> "Pay rebate on other heavy oil supplied for heating or engine use",
      "HO105SUB"                                                     -> "Payment of duty on aviation turbine fuel for private pleasure flying",
      "HO930"                                                        -> "Biofuels",
      "HO930SUB"                                                     -> "Excise duty return and payment of duty for biofuels and other fuel substitutes",
      "INT-NATIONAL"                                                 -> "Tax Credit Digial Change of Circumstance",
      "InternationalCaseworkersCA3822"                               -> "International Caseworkers Improvements (Employee)",
      "InternationalCaseworkersCA3837"                               -> "International Caseworkers Improvements (Employer)",
      "INVALID"                                                      -> "Invalid",
      "IOSSDe-registration"                                          -> "Tell HMRC about changes to registration with VAT import one stop shop in EU",
      "IPR1"                                                         -> "Apply for action to protect your intellectual property rights",
      "IPR2"                                                         -> "Report goods that infringe your intellectual property rights",
      "IPR3"                                                         -> "Apply to extend your application to protect your intellectual property",
      "IPT1"                                                         -> "Insurance Premium Tax Registration",
      "IPT100"                                                       -> "Insurance Premium Tax",
      "ISAMNOCSUB"                                                   -> "ISA manager notification of changes",
      "JobRetentionSchemeRevocation"                                 -> "Job Retention Scheme Revocation",
      "L2PSUB"                                                       -> "Reclaim tax paid by close companies on loans to participators",
      "L5SUB"                                                        -> "Application for a licence to carry on an Excise Trade",
      "LT1"                                                          -> "Landfill Tax Registration",
      "LT1BSUB"                                                      -> "Landfill Tax notification of changes to site details",
      "LT2SUB"                                                       -> "Landfill Tax partnership details",
      "LT100"                                                        -> "Landfill Tax Return",
      "LT769SUB"                                                     -> "Landfill Tax provide insolvency details",
      "Makeclaimforextendedlosscarryback"                            -> "Make claim for extended loss carry back",
      "MCA-FORM18SUB"                                                -> "Transferring the Married Couple’s Allowance",
      "MODCA2SUB"                                                    -> "Application for National Insurance class 3 credits",
      "MODnotify-hmrc-about-uk-armed-forces-customs-declaration"     -> "Notify HMRC about UK Armed Forces customs declaration",
      "MSBGROWTH"                                                    -> "MSB Growth Support",
      "MTDVAT-RegistrationNotRequiredNotification"                   -> "Declare your business is not required to register for making tax digital (VAT)",
      "NETPOverseasUKVAT-registeredtraders-non-establishedtaxpayers" -> "Provide bank details for uk vat registered overseas trader",
      "NICNationalInsuranceRebates"                                  -> "NIC National Insurance Rebates",
      "NIGiantsSubsidiaries"                                         -> "NI Giants Subsidiaries",
      "NIPBE"                                                        -> "Tell HMRC Northern Ireland Permanent Establishment",
      "NIProtocolVATTraderWithdrawal"                                -> "Withdraw from Northern Ireland Protocol VAT",
      "NIVATTrader"                                                  -> "Declare your business trades in Northern Ireland",
      "NMWCompSUB"                                                   -> "Pay and Work Rights Complaint Form",
      "NoneligibilitySPBP"                                           -> "Tell employee not eligible statutory parental bereavement pay",
      "NotifyIntenttoDiscloseCJRSOverclaim"                          -> "Notify Intent to Disclose CJRS Overclaim",
      "NRL1e"                                                        -> "Non-resident landlord application for an individual",
      "NRL2-3"                                                       -> "Non resident landlord application for companies and trusts",
      "NRL2e"                                                        -> "Application to receive UK rental income without deduction of UK tax",
      "NRL4-5"                                                       -> "Non resident landlord application for letting agents",
      "NRL4e"                                                        -> "Application by UK letting agents to operate the Non Resident Landlords scheme",
      "NRLYSUB"                                                      -> "Non Resident Landlord Annual Information Return",
      "OverseasSABankDetails"                                        -> "Overseas SA Bank Details",
      "P1"                                                           -> "Tax Credit Digial Change of Circumstance",
      "P11DAmendments"                                               -> "P11D Amendments",
      "P11DBSUB"                                                     -> "Class 1A National Insurance contributions due on expenses and benefits",
      "P11DDbAmendments"                                             -> "P11D(b) Amendments",
      "P46Car"                                                       -> "Car provided for the private use of an employee or director",
      "P50"                                                          -> "Claiming tax back when you have stopped working",
      "P50SUB"                                                       -> "Claiming tax back when you have stopped working",
      "P50Z"                                                         -> "Claim for repayment of tax when you have stopped working: flexibly accessed pension",
      "P50ZSUB"                                                      -> "Claim for repayment of tax when you have stopped working: flexibly accessed pension",
      "P53"                                                          -> "Small pension taken as a lump sum: repayment claim",
      "P53SUB"                                                       -> "Small pension taken as a lump sum: repayment claim",
      "P53Z"                                                         -> "Flexibly accessed pension lump sum: repayment claim (current tax year)",
      "P55"                                                          -> "Flexibly accessed pension payment: repayment claim (current tax year)",
      "P55SUB"                                                       -> "Flexibly accessed pension payment: repayment claim (current tax year)",
      "P85"                                                          -> "Leaving the UK to claim tax relief or any tax refund you’re owed",
      "P87SUB"                                                       -> "Tax relief for expenses of employment",
      "P350"                                                         -> "PAYE: Employer Annual Return election",
      "P626PSARequestAmend"                                          -> "Request amend PSA (Paye Settlement Agreement)",
      "PAYENiCoCSUB"                                                 -> "Notification of a change in personal details",
      "penalty"                                                      -> "Penalty Enquiry (Secure Messaging Form)",
      "PlasticPackagingTaxEnquiry"                                   -> "Plastic Packaging Tax Enquiry",
      "PlasticPackagingTaxRegistration"                              -> "Plastic Packaging Tax Registration",
      "PODS"                                                         -> "Pension Online Digital Service",
      "PPTFinalReturn"                                               -> "Plastic Packaging Tax Final Return and amendments",
      "PPTRequestaRefund"                                            -> "request-a-plastic-packaging-tax-repayment",
      "PSA1"                                                         -> "Paye Settlement Agreement",
      "PT_CertOfRes"                                                 -> "Request for certificate of residence in the UK",
      "PT_CertResFI"                                                 -> "Application for Certificate of Residence in the UK: Further information",
      "PTCOMPSUB"                                                    -> "Make your complaint online",
      "QAHC"                                                         -> "Qualifying Asset Holding Company",
      "Qualifyingcompaniesexemptionelection"                         -> "Qualifying companies exemption election",
      "R38EXPATSUB"                                                  -> "Expat tax claim",
      "R39_EN"                                                       -> "Claim a tax refund",
      "R40SUB"                                                       -> "Claim for repayment of tax deducted from savings and investments",
      "R44SUB"                                                       -> "Request for Seafarers NT Code",
      "RCGTSUB"                                                      -> "Report Capital Gains Tax for UK residents",
      "RDEC"                                                         -> "Research & Development",
      "RDPreNotification"                                            -> "R&D Pre Notification",
      "RDSME"                                                        -> "Research & Development (SME)",
      "ReclaimNon-UKResidentStampDutyLandTaxSurcharge"               -> "Reclaim Non-UK Resident Stamp Duty Land Tax Surcharge",
      "RecordClaimsSPBP"                                             -> "Record claims Statutory Parental Bereavement Pay",
      "RepayEatOuttoHelpOutGrant"                                    -> "Repay Eat Out to Help Out Grant",
      "RepaySEISSGrantMoney"                                         -> "Repay Self Emplyment Income Support Scheme Grant Money",
      "RES1"                                                         -> "Apply for certificate of residence",
      "Reviewself-employmentincomesupportschemegrantamount"          -> "Request a Review of SEISS Grant Amount",
      "REXSUB"                                                       -> "Application to become a registered exporter",
      "S690SUB"                                                      -> "Application for a Section 690 or informal treaty direction",
      "SA303"                                                        -> "Claim to reduce payments on account",
      "SA400"                                                        -> "Registering a partnership for Self Assessment",
      "SA700"                                                        -> "Tax return for a non-resident company liable for income tax",
      "SA4001"                                                       -> "Register a partner or a partnership for Self Assessment",
      "SAASUB"                                                       -> "Self Assessment: appeal against a late filing penalty",
      "SACSUB"                                                       -> "Self Assessment: Request removal from Self Assessment",
      "SDLT16"                                                       -> "Apply for a repayment of 3% Stamp Duty Land Tax",
      "SDLT16SUB"                                                    -> "Apply for a repayment of 3% Stamp Duty Land Tax",
      "SEISSCessationDeclarationBeforeGrantReceived"                 -> "Confirm whether you stopped trading before you claimed a Self-Employment Income Support Scheme Grant",
      "SEISSRequestaReviewofEligibility-NewChild"                    -> "Ask HMRC to verify you had a new child which affected your eligibility for the Self-Employment Support Scheme",
      "SEISSRequestaReviewofEligibility"                             -> "Review of Eligibility to Self Employed Income Support Scheme",
      "SEISSROOG"                                                    -> "Agree to pay Self-Employment Support Scheme Grant",
      "SEISSTellHMRCaboutamendmenttoTaxReturn"                       -> "SEISS Tell HMRC about amendment to Tax Return",
      "SettleDisguisedRenumerationasanIndividual"                    -> "Settle Disguised Renumeration as an Individual",
      "SP1SUB"                                                       -> "Application for End-Use Relief",
      "SP2SUB"                                                       -> "Application for a customs warehouse",
      "SP3SUB"                                                       -> "Application for Inward Processing Relief",
      "SP4SUB"                                                       -> "Application for Outward Processing Relief",
      "SP5SUB"                                                       -> "Application for Temporary Admission",
      "SPTU"                                                         -> "State Pension Top Up Request",
      "support-research-and-development-tax-claim"                   -> "Support research and development tax claim",
      "TC122SUB"                                                     -> "Tax Credits: Compliance",
      "TC846SUB"                                                     -> "Tax credits: Overpayment",
      "TC1133SUB"                                                    -> "Tax Credits: Tell us about financial hardship and household income and costs",
      "Tellhmrcyouareregisteredforvatimportonestopshopineu"          -> "Tell HMRC you are registered for VAT import one stop shop in EU",
      "TES1"                                                         -> "Tell us about income from employment or pension",
      "TES2"                                                         -> "Tell us about company benefits",
      "TES3"                                                         -> "Tell us about your Taxable State Benefit",
      "TES4"                                                         -> "Tell us about other income",
      "TES5"                                                         -> "Tell us about investment income",
      "TES7"                                                         -> "Tell us about your tax free allowance",
      "TES_FIN_SUB"                                                  -> "Tell us how you want to pay the estimated tax you owe",
      "TOR"                                                          -> "Transfer of Residence",
      "Transparencyelection"                                         -> "Transparency election",
      "TRC1"                                                         -> "Application to register for the Temporary Registered Consignee scheme",
      "TRNGIP"                                                       -> "Register a non-resident company for corporation tax",
      "TrustRegistrationService"                                     -> "Trust Registration Service - make a data request",
      "TrustReporting"                                               -> "Trust Registration Service - report a discrepency",
      "TSP"                                                          -> "Transitional Simplified Procedures",
      "TSPChief"                                                     -> "Activate a Badge to make a Chief Declaration",
      "TSPRevocation"                                                -> "Cancel a TSP Registration",
      "UncertainTaxTreatment"                                        -> "Notfify HMRC about an uncertain tax treatment",
      "UpdateGBEORIDetails"                                          -> "Update GB EORI Details",
      "VAT126"                                                       -> "Claim a VAT refund if not VAT registered",
      "VAT600AASUB"                                                  -> "Application to join the Annual Accounting Scheme",
      "VAT652"                                                       -> "Notification of errors on VAT returns",
      "VATFPRC"                                                      -> "Send details to support VAT repayment",
      "VCSAA"                                                        -> "Venture Capitals Non-Statutory",
      "VCSEIS1"                                                      -> "Submit Enterprise Investment Scheme compliance statement EIS to HMRC",
      "VCSSEIS1"                                                     -> "Submit Seed Enterprise Investment Scheme compliance statement SEIS1 to HMRC",
      "VCSSITR1"                                                     -> "Venture Capitals",
      "Vishing"                                                      -> "Report a suspicious HMRC phone call",
      "vol-overpay"                                                  -> "SEISS - Tell HMRC about an amendment to your tax return",
      "vol-repay1"                                                   -> "Repay Self-Employment Income Support Scheme grant money",
      "vol-repay2"                                                   -> "Repay Self-Employment Income Support Scheme grant money",
      "WMW1SUB"                                                      -> "Application for a licence as a wine or made-wine producer or commercial grower",
      "WTCAPSUB"                                                     -> "Tax credits: if you think a decision is wrong"
    )
  }

  def getFormName(formId: String): String = FormNames.getOrElse(formId, formId)
}
